fastlane_version "2.68.2"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload Max width layouts"
  lane :release_max_width_layouts do
    gradle(task: "clean")
    gradle(task: ":max-width-layouts:install")
    gradle(task: ":max-width-layouts:bintrayUpload")
  end

  desc "Upload Max width layouts Anko Extensions"
  lane :release_max_width_layouts_anko do
    gradle(task: "clean")
    gradle(task: ":max-width-layouts-anko:install")
    gradle(task: ":max-width-layouts-anko:bintrayUpload")
  end

  desc "Upload Progress Button"
  lane :release_progress_button do
    gradle(task: "clean")
    gradle(task: ":button-progress:install")
    gradle(task: ":button-progress:bintrayUpload")
  end

  desc "Deploy all libs to bintray"
  lane :deploy do
    #release_max_width_layouts
    #release_max_width_layouts_anko
    #release_progress_button
    deploy_module_bintray(module_name: "button-countdown", should_clean: true)
    #release_module(module: "button-countdown-rx")
  end

  private_lane :release_module do |options|
    module_name = options[:module]
    UI.message "Deploying module: #{module_name} to bintray"
    gradle(task: "clean")
    gradle(task: ":#{module_name}:install")
    gradle(task: ":#{module_name}:bintrayUpload")
    UI.message "Module uploaded: #{module_name} to bintray, go to bintray to upload to JCenter."
  end
end
